# Theory

## Introduction

- Phylogenetic reconstruction typically involves assuming that the sequences have evolved in a tree like way
- Recombination can lead to different regions of the genome having different evolutionary histories
  - Different trees for different regions
  - Overall, a *phylogenetic network*
  
## The impact of recombination

- Recombination can lead to (incorrect) 'star-like' trees
- Recombination can lead to incorrect estimates of evolutionary rates

## Recombination clues

- Outlying sequences
- Sequences isolated between clusters of similar sequences
- Significantly different trees from different parts of the genome

## Testing for recombination

- A comprehensive list of recombination analysis/detection software is maintained by David Robertson's lab [here](http://bioinf.man.ac.uk/robertson/recombination/programs.shtml)

## Approaches for recombination

- The best way to detect recombination depends on the pattern of recombination
  - Single recombinant sequence or several
  - Single breakpoint
  - Recombinant segment

## Examples of recombinant structures in HIV

- Take a look at [this list of recombinant forms of HIV](http://www.hiv.lanl.gov/content/sequence/HIV/CRFs/CRFs.html)
- This shows how rich recombinant structure can be
