# Practice

## Introduction

There are two widely used approaches to getting a time-stamped phylogeny or 'time tree'
  - 'Clockify' a maximum likelihood tree
    - Rate smoothing
    - Least squares dating
  - Fit a model that explicitly considers a strict or molecular clock

## Rate smoothing with ```chronos```

- Rate smoothing involves constraining a tree to have clock-like branch lengths, but allowing the evolutionary rate to vary in a possibly complex manner
- Given a *fixed*, *rooted* phylogeny, and a set of temporal constraints on sampling time, the function ```chronos``` will return a time tree
  - We will use a slightly modified version of the code

## Rooting the tree

- ```chronos``` needs a rooted tree
- We can estimate the root of the tree by maximising the association between the root-to-tip distance and the sampling times
- The function ```rtt``` in the library ```ape``` allows one to do this

## Least squares dating

- Least squares dating, implemented in a program [LSD](http://www.atgc-montpellier.fr/LSD/) also takes a fixed tree, and also estimates the root
- We can use R to generate the data files and run ```lsd```

## Bayesian approaches

- We can also fit phylogenies with time constraints using the popular Bayesian phylogenetic programs BEAST (version [1](http://beast.bio.ed.ac.uk) or [2](http://beast2.org)) and [MrBayes](http://mrbayes.sourceforge.net/)
- R can help to generate the input files for these programs

